import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import { Button } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Bee-Wary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Welcome to Bee-Wary</h1>
        <Button variant="filled">Test Button om te zien of Mantine werkt</Button>
        <p className={styles.description}>Footer voor Bee-Wary</p>
      </main>
    </>
  );
}
